#!/usr/bin/env python3
"""Reproduce the transition-path energy scan and the configurational-entropy
estimate on the open->closed morph.

The morph is nine identical-topology all-atom frames (data/morph/relaxed_0..8.pdb,
4447 atoms each) generated by Cα-displacement interpolation between the open and
closed endpoints followed by Cα-restrained minimisation. Because a total energy
is only comparable across an identical atom set, we read the SIGN of the gradient,
not an absolute barrier.

  Energy scan
    AMBER ff14SB + GBn2 implicit solvent single-point energies (computed here
    with OpenMM), and (optionally) MACE-OFF neural-network energies if the mace
    package is installed. AMBER must place the minimum at the closed end; when
    MACE is available, that independent scan must do the same.
  Entropy
    ANM quasi-harmonic configurational entropy difference between the open and
    closed morph endpoints, ΔS = ½ Σ ln(λ_open/λ_closed) over all non-trivial
    modes (units of k_B). Reported for completeness only; the sign/magnitude are
    mode-count-dependent and are NOT interpreted as a thermodynamic quantity.

Outputs
  crbn_energy_scan.npz    amber_kcal (9,), mace_kcal (9, if available), coord (9,)
  crbn_entropy.json       dS_all_kB and per-mode-count sensitivity

Usage:  python scripts/reproduce_energy_entropy.py [--verify]
"""
import os, sys, json
os.environ.setdefault("KMP_AFFINITY", "disabled")
import numpy as np

MORPH = "data/morph/relaxed_{}.pdb"
NF = 9
CUTOFF = 15.0

def amber_gbsa_scan():
    from openmm.app import PDBFile, ForceField, NoCutoff
    from openmm import LangevinIntegrator, Context, Platform
    from openmm.unit import kelvin, picosecond, femtosecond, kilocalorie_per_mole
    ff = ForceField("amber14-all.xml", "implicit/gbn2.xml")
    E = []
    for i in range(NF):
        pdb = PDBFile(MORPH.format(i))
        system = ff.createSystem(pdb.topology, nonbondedMethod=NoCutoff, constraints=None)
        ctx = Context(system, LangevinIntegrator(300*kelvin, 1/picosecond, 1*femtosecond),
                      Platform.getPlatformByName("CPU"))
        ctx.setPositions(pdb.positions)
        E.append(ctx.getState(getEnergy=True).getPotentialEnergy().value_in_unit(kilocalorie_per_mole))
        del ctx
    E = np.array(E)
    return E - E.min()

def mace_scan():
    try:
        from ase.io import read
        from mace.calculators import mace_off
    except Exception:
        return None
    calc = mace_off(model="small", device="cpu", default_dtype="float32")
    E = []
    for i in range(NF):
        a = read(MORPH.format(i)); a.calc = calc
        E.append(a.get_potential_energy() * 23.06)   # eV -> kcal/mol
    E = np.array(E)
    return E - E.min()

def read_ca(pdb):
    return np.array([[float(l[30:38]), float(l[38:46]), float(l[46:54])]
                     for l in open(pdb) if l.startswith("ATOM") and l[12:16].strip() == "CA"])

def anm_eigs(coords, cutoff=CUTOFF):
    n = len(coords); H = np.zeros((3*n, 3*n))
    for i in range(n):
        for j in range(i+1, n):
            d = coords[j]-coords[i]; r = np.linalg.norm(d)
            if r <= cutoff:
                k = np.outer(d, d)/r**2
                H[3*i:3*i+3, 3*j:3*j+3] = -k; H[3*j:3*j+3, 3*i:3*i+3] = -k
                H[3*i:3*i+3, 3*i:3*i+3] += k; H[3*j:3*j+3, 3*j:3*j+3] += k
    w = np.linalg.eigvalsh(H)
    return w[w > 1e-9]

def main():
    verify = "--verify" in sys.argv
    amber = amber_gbsa_scan()
    coord = np.linspace(0, 1, NF)
    print(f"AMBER/GBSA rel (kcal/mol): {amber.round(0)}")
    print(f"  argmin frame {amber.argmin()} (coord {coord[amber.argmin()]:.3f})")
    mace = mace_scan()
    if mace is not None:
        print(f"MACE-OFF rel (kcal/mol): {mace.round(0)}  argmin frame {mace.argmin()}")
    wo = anm_eigs(read_ca(MORPH.format(0))); wc = anm_eigs(read_ca(MORPH.format(NF-1)))
    dS_all = 0.5*np.sum(np.log(wo/wc))
    sens = {}
    for k in (20, 50, 100, 200):
        sens[k] = float(0.5*np.sum(np.log(wo[:k]/wc[:k])))
    print(f"all-mode quasi-harmonic ΔS (open->closed) = {dS_all:.1f} k_B")
    if not verify:
        np.savez("data/crbn_energy_scan.npz", amber_kcal=amber, coord=coord,
                 **({"mace_kcal": mace} if mace is not None else {}))
        with open("data/crbn_entropy.json", "w", encoding="utf-8") as fh:
            json.dump({"dS_all_kB": float(dS_all), "mode_count_sensitivity_kB": sens},
                      fh, indent=1)
        print("wrote data/crbn_energy_scan.npz, crbn_entropy.json")

    if verify:
        assert amber.argmin() == 7, amber.argmin()
        full_validation = mace is not None
        if full_validation:
            assert mace.argmin() == 7, mace.argmin()
        assert abs(dS_all - (-23.3)) < 1.0, dS_all
        if full_validation:
            print(f"verify OK (full): AMBER and MACE minima at closed (frame 7); "
                  f"ΔS = {dS_all:.1f} k_B (committed -23, all-mode quasi-harmonic)")
        else:
            print(f"verify OK (partial): AMBER minimum at closed (frame 7) and "
                  f"ΔS = {dS_all:.1f} k_B (committed -23, all-mode quasi-harmonic); "
                  "MACE-OFF unavailable, so neural-network energy validation was skipped")

if __name__ == "__main__":
    main()
